FROM golang:latest

WORKDIR /app

COPY evilginx3/ /app/evilginx3/
COPY scripts/evilginx3-setup.sh /app/evilginx3-setup.sh
COPY scripts/entrypoint.sh /app/entrypoint.sh

RUN chmod +x /app/evilginx3-setup.sh
RUN chmod +x /app/entrypoint.sh
RUN /app/evilginx3-setup.sh

ENTRYPOINT ["/app/entrypoint.sh", "tail", "-f", "/dev/null"]
